### ISSUE TITLE
why the flash-cosine-sim-attention is slower than plain-cosine transformer?

### ISSUE THREAD

**Issue by 3bobo** [lucidrains/flash-cosine-sim-attention#1]
Thanks for your work! I test the flash-cosine-sim-attention by running `benchmark.py` in my 2080, while it shows the flash is slower than plain, especially for large seq_len. Why does the result conflict with the paper?

**Comment by lucidrains** [comment]
@3bobo hello and thanks for your interest!

this repository is far from done

when it is fully completed I'll remove the wip flag from the title

**Comment by 3bobo** [comment]
Great! Thanks for your work!
