### ISSUE TITLE
Performance compared to plain version

### ISSUE THREAD

**Issue by inspirit** [lucidrains/flash-cosine-sim-attention#2]
Hey! Great work as usual! :) 
Correct me if I'm wrong but it seems that cuda version is still times slower compared to plain impl?

**Comment by lucidrains** [comment]
@inspirit hey Eugene! yea it is really far from done actually

I'll remove the work in progress (wip) flag in the title when it is done

**Comment by lucidrains** [comment]
@inspirit feel free to contribute if you know any CUDA 😄 i'm very beginner but aiming to be average proficiency in a year

**Comment by lucidrains** [comment]
@inspirit feel free to contribute if you know any CUDA :)

**Comment by inspirit** [comment]
well my cuda skills are about as good as null :) will do the reviewing as much as I can follow

**Comment by lucidrains** [comment]
@inspirit same, i'm starting from zero too 😄 @ahennequ is giving me a lot of guidance

**Comment by inspirit** [comment]
Hey! thanks for the update i was closely following all updates :) and will try it asap when i have a chance
