### ISSUE TITLE
Pip Install Fails

### ISSUE THREAD

**Issue by kradonneoh** [lucidrains/flash-cosine-sim-attention#5]
Hey!

I attempted to install this package using pip, but ran into 

```
flash_cosine_sim_attention/flash_cosine_sim_attention_cuda.cu:10:10: fatal error: dispatch.h: No such file or directory
         10 | #include "dispatch.h"
            |          ^~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/nvcc' failed with exit status 1
```

Cloning the repo and running `make install` worked just fine, so I'm assuming `setup.py` (or whatever makes the pip package) just isn't including the `dispatch.h` header file.

**Comment by lucidrains** [comment]
@kradonneoh oh shoot, do you want to try 0.1.14? https://github.com/lucidrains/flash-cosine-sim-attention/commit/4afa8a00690e6ffe63c26d00c07f5762d63faf3b

**Comment by kradonneoh** [comment]
Seems to be working :-)

**Comment by lucidrains** [comment]
@kradonneoh nice :^)
